//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LumaflyKnight.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LumaflyKnight.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Pre_Menu_Intro&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Menu_Title&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Quit_To_Menu&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;BetaEnd&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Knight_Pickup&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Opening_Sequence&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Tutorial_01&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Town&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Cinematic_Stag_travel&quot;:{&quot;lamps&quot;:{},&quot;enemies&quot;:{}},&quot;Room_Town_Stag_Station&quot;:{&quot;lamps&quot;:{&quot;/station_pole/Stag_Pole_Tall_Break (2)/lamp_bug_escape (7)&quot;:{&quot;deletePath&quot;:&quot;/station_pole/Stag_Pole_Tall_Br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
    }
}
